# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitpocket', '0003_profile_game_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bet_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='pot',
            field=models.IntegerField(default=0),
        ),
    ]
