# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitpocket', '0004_auto_20170315_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cost',
            field=models.IntegerField(default=2),
        ),
    ]
