# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitpocket', '0005_profile_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
